# Autorise le compte guest à se connecter depuis l'hôte
# lorsque RabbitMQ fonctionne dans un conteneur Docker.
#
# Cette option est uniquement acceptable pour du développement local.
loopback_users = none

# Port utilisé par les clients AMQP.
listeners.tcp.default = 5672

# Port utilisé par l'interface web RabbitMQ.
management.tcp.port = 15672